"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";

type Props = {
  initialContent: string;
  verifyToken: string;
};

function formatToday(): string {
  return new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric"
  });
}

function splitBodyAndClosing(content: string): { body: string[]; closing: string[] } {
  const normalized = content.replace(/\r\n/g, "\n").trim();
  const marker = normalized.toLowerCase().lastIndexOf("\nsincerely,");

  if (marker === -1) {
    return {
      body: normalized.split(/\n\s*\n/).map((x) => x.trim()).filter(Boolean),
      closing: []
    };
  }

  const body = normalized
    .slice(0, marker)
    .trim()
    .split(/\n\s*\n/)
    .map((x) => x.trim())
    .filter(Boolean);

  const closing = normalized
    .slice(marker + 1)
    .trim()
    .split("\n")
    .map((x) => x.trim())
    .filter(Boolean);

  return { body, closing };
}

function buildReferenceId(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i += 1) {
    hash = (hash * 31 + content.charCodeAt(i)) >>> 0;
  }
  const dateTag = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return `ZYNTIQ-LOR-${dateTag}-${hash.toString(16).slice(0, 6).toUpperCase()}`;
}

export default function LORPreview({ initialContent, verifyToken }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);

  const sections = useMemo(() => splitBodyAndClosing(initialContent), [initialContent]);
  const referenceId = useMemo(() => buildReferenceId(initialContent), [initialContent]);

  useEffect(() => {
    if (typeof window !== "undefined" && verifyToken) {
      const origin = window.location.origin;
      const verificationUrl = `${origin}/verify?token=${verifyToken}`;
      QRCode.toDataURL(verificationUrl, { margin: 1, width: 128 })
        .then(setQrCodeUrl)
        .catch(console.error);
    }
  }, [verifyToken]);

  async function handleDownload() {
    setError(null);
    setLoading(true);

    try {
      const res = await fetch("/api/generate-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token: verifyToken, fileName: "LOR.pdf" })
      });

      if (!res.ok) throw new Error("Failed to generate LOR");

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "LOR.pdf";
      a.rel = "noopener";
      a.click();

      setTimeout(() => URL.revokeObjectURL(url), 2000);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="card form-grid">
      <h3 className="panel-title">Preview LOR</h3>

      <div className="lor-paper">
        <div className="lor-header">
          <Image
            className="lor-logo"
            src="/assets/logo.png"
            alt="Company logo"
            width={128}
            height={36}
          />
          <div className="lor-company-block">
            <div>Zyntiq (OPC) Pvt Ltd</div>
            <div className="lor-date">Date: {formatToday()}</div>
          </div>
        </div>

        <h2 className="lor-title">Letter of Recommendation</h2>
        <p className="lor-subtitle">To whomsoever it may concern</p>

        <div className="lor-body">
          {sections.body.map((paragraph, idx) => (
            <p key={`body-${idx}`}>{paragraph}</p>
          ))}
          <p style={{ marginTop: "2px" }}>
            We wish them success in their future academic and professional endeavors.
          </p>
        </div>

        {sections.closing.length > 0 ? (
          <div className="lor-closing">
            {sections.closing.map((line, idx) => (
              <p key={`close-${idx}`}>{line}</p>
            ))}
            <div className="lor-reference">Reference ID: {referenceId}</div>

            <Image
              className="lor-stamp"
              src="/assets/seal&sign.png"
              alt="Seal and signature"
              width={98}
              height={98}
            />
            {qrCodeUrl && (
              <img
                className="lor-qr"
                src={qrCodeUrl}
                alt="Verification QR Code"
              />
            )}
          </div>
        ) : null}

        <div className="lor-footer-wrap">
          <div>contact@zyntiq.in</div>
          <div>Generated by Zyntiq LOR Portal</div>
        </div>
      </div>

      <div className="row">
        <button className="btn" type="button" onClick={handleDownload} disabled={loading}>
          {loading ? "Preparing..." : "Download"}
        </button>
      </div>

      {error ? <p className="error">{error}</p> : null}
    </section>
  );
}